### ISSUE TITLE
Dont find the index.tlp

### ISSUE THREAD

**Issue by estvmachine** [cakephp/TwigView#24]
Hi i follow your instructions and delete an index.ctp and replace for an index.tlp but dont recognize, what i have to do?

Do you have a project example in github maybe?

![image](https://cloud.githubusercontent.com/assets/2062668/16676272/bff816a0-4496-11e6-8104-3115d671ef8d.png)

**Comment by WyriHaximus** [comment]
Make sure it is `.tpl` and not `.tlp`

**Comment by inoas** [comment]
@estvmachine I think you can close this issue now. Also the recommended extension is .twig now. That should also make such typos less likely ;)

**Comment by Oxicode** [comment]
+1 .twig
