### ISSUE TITLE
Using Html.addCrumb generates an error Object of class Cake\View\Helper\HtmlHelper could not be converted to string

### ISSUE THREAD

**Issue by vonboth** [cakephp/TwigView#27]
When Using hte addCrumb method with the HtmlHelper like so:
`{{ Html.addCrumb('Some Crumb') }}`
one get's the error

`Object of class Cake\View\Helper\HtmlHelper could not be converted to string [ROOT/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code, line 25]`

**Comment by WyriHaximus** [comment]
Yeah that is correct, ran into this the other day as well and working on a fix for it.

**Comment by vonboth** [comment]
Ok, I found out some more regarding this issue.
The error comes from the function 'twig_escape_filter' in twig/twig/lib/Twig/Extension/Core.php
The problem seems to be that Twig wants to escape the return value of 'addCrumb' but it returns an Object while the filter expects a string to be passed in (or at least an object with a __toString() method)

So either Cake (add __toString) or Twig (catch an object without __toSring) needs to be changed to catch the error which is both not suitable for me.

The easiest is to create a new filter method e.g. a 'none'-Filter which contains a simple return statement that has to be used with 'addCrumb'.

I will create another PR and you can think about pulling it in.
Cheers

**Comment by ADmad** [comment]
This should be fixed by #61

**Comment by HavokInspiration** [comment]
The `do` method on Twig should be used instead :

```
{% do Html.addCrumb('Some Crumb') %}
```

Refs in twig doc : https://twig.symfony.com/doc/1.x/tags/do.html
