### ISSUE TITLE
Not setting options for {% element %} throws error

### ISSUE THREAD

**Issue by edggids** [cakephp/TwigView#49]
Hi,

if you don't set options for element it will fail as it passes null to $compiler->subcompile()

in Lib\Twig\Node\Element.php
line: 65

```
$options = $this->getNode('options');
if ($data!== null) {
    $compiler->raw(',');
     $compiler->subcompile($options);
}
```

I think it should check for $options not $data.

Thanks.

**Comment by WyriHaximus** [comment]
Good point 👍 , could you make a PR, don't have time to test and fix it right now

**Comment by ADmad** [comment]
Has this been already fixed?

https://github.com/WyriHaximus/TwigView/blob/5da1061417bfbcf00482cf5a13498f05fcfd2419/src/Lib/Twig/Node/Element.php#L68-L72
