### ISSUE TITLE
Specialchar don't displayed with helper 

### ISSUE THREAD

**Issue by ozee31** [cakephp/TwigView#59]
I try to display a specialchar with a helper but doesn't work : 

```php
{{ Paginator.first('&laquo;')|raw }}
{{ Paginator.first('&laquo;'|e)|raw }}
{{ Paginator.first('&laquo;'|escape)|raw }}
{{ Paginator.first('&laquo;'|raw)|raw }}
```

**Comment by inoas** [comment]
Without reading the docs, to me it should display `&laquo;`
Try inserting the real utf8-symbol instead of the html-entity.
