### ISSUE TITLE
Issue with Twig when trying to bake in cakephp 3.x

### ISSUE THREAD

**Issue by clementcrownrise** [cakephp/TwigView#85]
c:\wamp\www\landmarkcurrent\bin>cake bake all faculties
Bake All
---------------------------------------------------------------
One moment while associations are detected.
Exception: Unknown "as_array" filter. in [C:\wamp\www\landmarkcurrent\vendor\cakephp\bake\src\Template\Bake\Model\table.twig, line 50]
2018-04-12 12:22:52 Error: [Twig_Error_Syntax] Unknown "as_array" filter. in C:\wamp\www\landmarkcurrent\vendor\cakephp\bake\src\Template\Bake\Model\table.twig on line 50
Stack Trace:
#0 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\ExpressionParser.php(484): Twig_ExpressionParser->getFilterNodeClass('as_array', 50)
#1 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\ExpressionParser.php(469): Twig_ExpressionParser->parseFilterExpressionRaw(Object(Twig_Node_Expression_Name))
#2 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\ExpressionParser.php(323): Twig_ExpressionParser->parseFilterExpression(Object(Twig_Node_Expression_Name))
#3 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\ExpressionParser.php(215): Twig_ExpressionParser->parsePostfixExpression(Object(Twig_Node_Expression_Name))
#4 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\ExpressionParser.php(102): Twig_ExpressionParser->parsePrimaryExpression()
#5 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\ExpressionParser.php(55): Twig_ExpressionParser->getPrimary()
#6 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\Parser.php(149): Twig_ExpressionParser->parseExpression()
#7 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\TokenParser\If.php(45): Twig_Parser->subparse(Array)
#8 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\Parser.php(192): Twig_TokenParser_If->parse(Object(Twig_Token))
#9 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\TokenParser\If.php(36): Twig_Parser->subparse(Array)
#10 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\Parser.php(192): Twig_TokenParser_If->parse(Object(Twig_Token))
#11 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\Parser.php(105): Twig_Parser->subparse(NULL, false)
#12 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\Environment.php(716): Twig_Parser->parse(Object(Twig_TokenStream))
#13 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\Environment.php(774): Twig_Environment->parse(Object(Twig_TokenStream))
#14 C:\wamp\www\landmarkcurrent\vendor\twig\twig\lib\Twig\Environment.php(452): Twig_Environment->compileSource(Object(Twig_Source))
#15 C:\wamp\www\landmarkcurrent\vendor\wyrihaximus\twig-view\src\View\TwigView.php(180): Twig_Environment->loadTemplate('C:\\wamp\\www\\lan...')
#16 C:\wamp\www\landmarkcurrent\vendor\cakephp\bake\src\View\BakeView.php(146): WyriHaximus\TwigView\View\TwigView->_render('C:\\wamp\\www\\lan...')
#17 C:\wamp\www\landmarkcurrent\vendor\cakephp\bake\src\Shell\Task\BakeTemplateTask.php(89): Bake\View\BakeView->render('Model/table')
#18 C:\wamp\www\landmarkcurrent\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(956): Bake\Shell\Task\BakeTemplateTask->generate('Model/table')
#19 C:\wamp\www\landmarkcurrent\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(114): Bake\Shell\Task\ModelTask->bakeTable(Object(Cake\ORM\Table), Array)
#20 C:\wamp\www\landmarkcurrent\vendor\cakephp\bake\src\Shell\Task\ModelTask.php(100): Bake\Shell\Task\ModelTask->bake('Faculties')
#21 C:\wamp\www\landmarkcurrent\vendor\cakephp\bake\src\Shell\BakeShell.php(272): Bake\Shell\Task\ModelTask->main('Faculties')
#22 C:\wamp\www\landmarkcurrent\vendor\cakephp\cakephp\src\Collection\CollectionTrait.php(51): Bake\Shell\BakeShell->Bake\Shell\{closure}('faculties', 0)
#23 C:\wamp\www\landmarkcurrent\vendor\cakephp\bake\src\Shell\BakeShell.php(273): Cake\Collection\Collection->each(Object(Closure))
#24 C:\wamp\www\landmarkcurrent\vendor\cakephp\cakephp\src\Console\Shell.php(493): Bake\Shell\BakeShell->all('faculties')
#25 C:\wamp\www\landmarkcurrent\vendor\cakephp\cakephp\src\Console\CommandRunner.php(141): Cake\Console\Shell->runCommand(Array, true)
#26 C:\wamp\www\landmarkcurrent\bin\cake.php(12): Cake\Console\CommandRunner->run(Array)
#27 {main}

**Comment by WyriHaximus** [comment]
Hey @clementcrownrise this plugin doesn't ship with an `as_array`. This seems related to https://github.com/cakephp/bake/issues/391 which should has been resolved with a documentation update at https://github.com/cakephp/docs/pull/5636 and available at https://book.cakephp.org/3.0/en/bake.html#installation 

Does that resolve your issue?
