### ISSUE TITLE
add missing inflectors

### ISSUE THREAD

**Issue by dereuromark** [cakephp/TwigView#95]
the newer ones seem missing as filter:

- `dasherize` maps to `Cake\Utility\Inflector::dasherize()`
- slug should be Text:slug() as Inflector::slug() is deprecated

also:

- autoParagraph => TextHelper::autoParagraph()
- autoLinkUrls => TextHelper::autoLinkUrls()

**Comment by WyriHaximus** [comment]
> the newer ones seem missing as filter:
> 
> * `dasherize` maps to `Cake\Utility\Inflector::dasherize()`
> * slug should be Text:slug() as Inflector::slug() is deprecated
> 
> also:
> 
> * autoParagraph => TextHelper::autoParagraph()
> * autoLinkUrls => TextHelper::autoLinkUrls()

Will add those through a PR, or are you already working on it?

> slightly unrelated
> why is number_format not numberFormat
> I seems the convention is camelBacked instead of under_scored for 99% of the methods.

Sounds like a good target to fix in the release for cake4

**Comment by dereuromark** [comment]
Nah, I am busy otherwise. Thanks for looking into it.

**Comment by WyriHaximus** [comment]
No problem working on it now.

These are interesting, been mainly using utility classes for things like this but these are actually inside a helper. The Helper element I'm working on should help with these two:

> * autoParagraph => TextHelper::autoParagraph()
> * autoLinkUrls => TextHelper::autoLinkUrls()

**Comment by WyriHaximus** [comment]
> * `slug` should be Text:slug() as Inflector::slug() is deprecated

Methods look rather different, is the outcome always the same regardless of which I use?

**Comment by ADmad** [comment]
> Methods look rather different, is the outcome always the same regardless of which I use?

For most practical uses cases it's the same.

**Comment by dereuromark** [comment]
I tested it and it looked quite similar in my cases, but if we want to make sure for all cases, maybe we should one and deprecate the other.

**Comment by WyriHaximus** [comment]
Was expecting `Inflector::slug()` to use `Text::slug()` internally due to the deprecation

**Comment by WyriHaximus** [comment]
Ok `4.3.6` has been released with the dasherize + @ADmad deprication notice bug fix.
